/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonTwo: typeof import('./src/components/MyButton/ButtonTwo/ButtonTwo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MyButton: typeof import('./src/components/MyButton/MyButton.vue')['default']
    Paginator: typeof import('./src/components/Paginator/Paginator.vue')['default']
    PrimePaginator: typeof import('./src/components/PrimePaginator/PrimePaginator.vue')['default']
    Task: typeof import('./src/components/Task/Task.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VuetiFyPaginator: typeof import('./src/components/VuetiFy/VuetiFyPaginator.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
